server:
  port: 8010
#  servlet:
#    context-path: /user


spring:
  application:
    name: User
#  datasource:
#    url: jdbc:mysql://localhost:3306/healthcare
#    username: root
#    password: admin
#  jpa:
#    database: mysql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  config:
#    import: configserver:http://localhost:8100
#  zipkin:
#    baseUrl: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
