
spring:
  application:
    name: eureka-server
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8050


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka
    fetch-registry: false
    register-with-eureka: false
