
spring:
  application:
    name: eureka-server

server:
  port: 8050


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka
    fetch-registry: false
    register-with-eureka: false
