server:
  port: 8082
  servlet:
    context-path: /order


spring:
  application:
    name: Order
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: admin


external-client:
  userClient:
    baseUrl: http://localhost:8081/user
  pharmacyClient:
    baseUrl: http://localhost:8080/pharmacy
