
server:
  port: 8100

spring:
  application:
    name: Config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Udaykumar37/HealthCare-Config
          default-label: main
        clone-on-start: true
#  zipkin:
#    baseUrl: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    # When multiple instances are used, we use port number 0. In such case the above property creates random instance id and helps eureka server in identifying multiple instances
