server:
  port: 8080
  servlet:
    context-path: /pharmacy


spring:
  application:
    name: Pharmacy
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: admin
